### PR TITLE
Add libs for SDK 27.

### PR DESCRIPTION
**Pull request by nezorflame**
lib/27/libfacenet.so
	lib/27/libfilterpack_facedetect.so

### CODE REVIEW

**Comment by nezorflame** [comment]
@SpasilliumNexus this is per https://github.com/opengapps/all/blob/master/HOWTO

**Comment by nezorflame** [comment]
Not sure that it's needed, though.

**Comment by SpasilliumNexus** [comment]
I'm not too sure myself. Wish I had a 32bit device to test this stuff on, as trying to get testers is really slow on responses. Is FaceLock API 27 too?

**Comment by nezorflame** [comment]
https://github.com/opengapps/all/pull/16

**Pull request merged**
